Arm control io
ChielBruin/tomatenplukkers pull request #20
Opened 2016-12-14 11:05 UTC by MaxGroenenboom

- [x] Added IO to arm control.
- [x] Cleaned up kpr_arm_control package.
- [x] Added io pin for the cutter.
- [x] Fixed the io sim not setting up the server properly when using the ur_sim.
- [x] Added a lot of debug code (that probably should have been removed...)

2016-12-14 11:53 UTC, ChielBruin requested changes
The functionality looks good. I made some comments about the style. In addition to all the small comments, your non-node code uses the ros services, that should only be accessed in the node. But this does not have to be changed right now and can be done  in the main PR to the master.

2016-12-14 11:53 UTC, ChielBruin commented on catkin_ws/src/cucumber_msgs/include/cucumber_msgs/CucumberContainer.h
> +		pose.orientation.w = 1.0;
Yeej quaternions :stuck_out_tongue:!

2016-12-14 11:53 UTC, ChielBruin commented on catkin_ws/src/kpr_arm_control/src/arm_control/arm_control.cpp
> +const float CUTTER_OPEN = 0x0; // Not sure about value
Values seem okay, @alexLouw please verify this. When he approves the values, the comments should be removed.

2016-12-14 11:53 UTC, ChielBruin commented on catkin_ws/src/kpr_arm_control/src/arm_control/arm_control.cpp
> +		return success;
Just return `false` this is a little quicker (and probably optimized that way during compilation)

2016-12-14 11:53 UTC, ChielBruin commented on catkin_ws/src/kpr_arm_control/src/arm_control/arm_control.cpp
> +bool startGrip() {
Please add some documentation to this method

2016-12-14 11:53 UTC, ChielBruin commented on catkin_ws/src/kpr_arm_control/src/arm_control/arm_control.cpp
> +bool cut() {
And here as well

2016-12-14 11:53 UTC, ChielBruin commented on catkin_ws/src/kpr_arm_control/src/arm_control/arm_control.cpp
> +	//TODO Not sure if a timeout should be here.
Probably not, but good to leave a reference for later

2016-12-14 11:53 UTC, ChielBruin commented on catkin_ws/src/kpr_arm_control/src/arm_control/arm_control.cpp
>  bool releaseGrip() {
Please add some documentation

2016-12-14 11:53 UTC, ChielBruin commented on catkin_ws/src/kpr_arm_control/src/arm_control/arm_control.cpp
> +	return io_state_client.call(io_message) && io_message.response.success;
As you keep reusing these 5 lines, you should create a function `bool setPin(pin, fun, state) {` that you call each time

2016-12-14 11:53 UTC, ChielBruin commented on catkin_ws/src/kpr_arm_control/src/arm_control/node_arm_control.cpp
> +//#include <tf/LinearMath/Transform.h> //TODO Remove later.
Why later and not now (as it is unused)?

2016-12-14 11:53 UTC, ChielBruin commented on catkin_ws/src/kpr_arm_control/src/arm_control/node_arm_control.cpp
> +//TODO Remove until here.
:see_no_evil:

2016-12-14 12:20 UTC, alexLouw commented on catkin_ws/src/kpr_arm_control/src/arm_control/arm_control.cpp
> +const float CUTTER_OPEN = 0x0; // Not sure about value
Cutter values are fine (since it is normally open), but the gripper values could be reversed (since it is normally closed).

2016-12-14 12:33 UTC, alexLouw requested changes
In arm_control.cpp the values of the gripper could be changed and the cutting function could be split in opening and closing

2016-12-14 12:33 UTC, alexLouw commented on catkin_ws/src/kpr_arm_control/src/arm_control/arm_control.cpp
> +	//TODO Not sure if a timeout should be here.
I think we should separate the closing and opening of the cutter, so that the we can read out its sensors and make a decision based on them.

2016-12-14 12:33 UTC, alexLouw commented on catkin_ws/src/kpr_arm_control/src/arm_control/arm_control.cpp
> +const float CUTTER_OPEN = 0x0; // Not sure about value
Cutter values are fine (since it is normally open), but the gripper values could be reversed (since it is normally closed).

2016-12-14 12:51 UTC, MaxGroenenboom commented on catkin_ws/src/kpr_arm_control/src/arm_control/arm_control.cpp
> +	//TODO Not sure if a timeout should be here.
I think it's best if that happens inside the cut function.

2016-12-14 18:52 UTC, ChielBruin requested changes
Two small things and you get my approval as it all seems fine now.

2016-12-14 18:52 UTC, ChielBruin commented on catkin_ws/src/kpr_arm_control/src/arm_control/arm_control.cpp
> +const float CUTTER_OPEN = 0x0; // Not sure about value
As these values are discussed with @alexLouw, the comments can be removed in my opinion

2016-12-14 18:52 UTC, ChielBruin commented on catkin_ws/src/kpr_arm_control/src/arm_control/arm_control.cpp
>   * @param [in] targetPose The target pose at the end of the action.
What does the `[in]` signify?

2016-12-14 18:52 UTC, ChielBruin commented on catkin_ws/src/kpr_arm_control/src/arm_control/arm_control.cpp
>   * @param [in] targetPose The target pose at the end of the action.
Nevermind, I found its meaning later in the diff

2016-12-14 18:52 UTC, ChielBruin commented on catkin_ws/src/kpr_testing/src/io_pins.py
> +	"DO4":["-	","-","Cutter"],
Spacing is off. Maybe a \t vs spaces

2016-12-15 09:35 UTC, ChielBruin approved these changes
Looks good now!

2016-12-15 09:43 UTC, merged