Saving and loading setting presets
ChielBruin/tomatenplukkers pull request #25
Opened 2016-12-16 15:06 UTC by ChielBruin

- Added setting loading and saving in the settings manager
- Added buttons in the interface that invoke this fnctionality

2016-12-16 16:45 UTC, MaxGroenenboom requested changes
I haven't tested the code yet, but it looks good.

2016-12-16 16:45 UTC, MaxGroenenboom commented on catkin_ws/src/kpr_interface/cfg/settings.json
> +{"maxCurvature": "100", "maxWeight": "4400", "minWeight": "300", "armSpeed": "100"}
Why do you save these as strings? JSON does support numbers (in this case floats I suppose)

2016-12-16 16:45 UTC, MaxGroenenboom commented on catkin_ws/src/kpr_interface/srv/SettingsIO.srv
> +# A status code that indicats the succes of the operation
Typo

2016-12-16 16:45 UTC, MaxGroenenboom commented on catkin_ws/src/kpr_interface/srv/SettingsIO.srv
> +uint8 succes
Another typo :P

2016-12-16 17:44 UTC, ChielBruin commented on catkin_ws/src/kpr_interface/cfg/settings.json
> +{"maxCurvature": "100", "maxWeight": "4400", "minWeight": "300", "armSpeed": "100"}
They are strings to be able to support multiple data formats and primarily to simplify the communication.

2016-12-16 17:44 UTC, ChielBruin commented on catkin_ws/src/kpr_interface/srv/SettingsIO.srv
> +# A status code that indicats the succes of the operation
Oops!

2016-12-16 19:01 UTC, MaxGroenenboom commented
Why not load the settings in the interface and send it to the settings manager instead? The interface already supports editing the settings.

2016-12-19 09:10 UTC, ChielBruin commented
The idea of the settings manager is that it performs all operations on the settings and provides an abstraction layer for all nodes that want to use this functionality. Therefore the settings manager is the correct location for the saving and loading of the settings.

2016-12-19 09:25 UTC, MaxGroenenboom commented
Works as it should :+1:

2016-12-19 09:25 UTC, MaxGroenenboom approved these changes

2016-12-19 09:29 UTC, merged