Added environment objects to planning scene.
ChielBruin/tomatenplukkers pull request #27
Opened 2016-12-20 13:51 UTC by MaxGroenenboom

Added some environment objects to the MoveIt! planning scene:
- The table the arm stands on.
- A backpanel to prevent the arm from using the space behind it (there would be other plants there).
- A temporary box representing the gripper.

Also added the option to enable the MoveIt! planning interface for live runs and to make it automatically enabled for testing runs. This interface is needed to view the added planning scene collision objects.

A first version of point cloud usage by the collision model has been added as well, but this has not been tested yet, and it doesn't have real parameters.

2016-12-21 09:08 UTC, ChielBruin requested changes
The code looks good, please address my comments and make it mergable again. Than we have to wait until travis has fixed itself

2016-12-21 09:08 UTC, ChielBruin commented on catkin_ws/src/universal_robot/ur5_moveit_config/launch/ur5_moveit_sensor_manager.launch.xml
>  </launch>
Why is this a .launch.xml file and not simply .launch?

2016-12-21 09:08 UTC, ChielBruin commented on catkin_ws/src/universal_robot/ur5_moveit_config/config/sensors_bumblebee.yaml
> +    filtered_cloud_topic: filtered_cloud
Please test this

2016-12-21 09:11 UTC, MaxGroenenboom commented on catkin_ws/src/universal_robot/ur5_moveit_config/launch/ur5_moveit_sensor_manager.launch.xml
>  </launch>
It's a default file in that project, I merely added some parameters to it ;)

2016-12-22 09:22 UTC, MaxGroenenboom commented on catkin_ws/src/universal_robot/ur5_moveit_config/config/sensors_bumblebee.yaml
> +    filtered_cloud_topic: filtered_cloud
I've tried testing it but currently `/filtered_cloud` doesn't return anything.

2016-12-22 09:49 UTC, ChielBruin commented on catkin_ws/src/universal_robot/ur5_moveit_config/config/sensors_bumblebee.yaml
> +    filtered_cloud_topic: filtered_cloud
Than it should be fixed before merging

2016-12-22 13:09 UTC, ChielBruin approved these changes

2016-12-22 13:09 UTC, merged